# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: highway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhighway.proto\x12\x05greet\"\x1e\n\x0eHighwayRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\rHighwaySender\x12\x32\n\x0bSendHighway\x12\x15.greet.HighwayRequest\x1a\x0c.greet.Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'highway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HIGHWAYREQUEST']._serialized_start=24
  _globals['_HIGHWAYREQUEST']._serialized_end=54
  _globals['_REPLY']._serialized_start=56
  _globals['_REPLY']._serialized_end=80
  _globals['_HIGHWAYSENDER']._serialized_start=82
  _globals['_HIGHWAYSENDER']._serialized_end=149
# @@protoc_insertion_point(module_scope)
