# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import highway_pb2 as highway__pb2


class HighwaySenderStub(object):
    """The highway data service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHighway = channel.unary_unary(
                '/greet.HighwaySender/SendHighway',
                request_serializer=highway__pb2.HighwayRequest.SerializeToString,
                response_deserializer=highway__pb2.Reply.FromString,
                )


class HighwaySenderServicer(object):
    """The highway data service definition
    """

    def SendHighway(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HighwaySenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHighway': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHighway,
                    request_deserializer=highway__pb2.HighwayRequest.FromString,
                    response_serializer=highway__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.HighwaySender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HighwaySender(object):
    """The highway data service definition
    """

    @staticmethod
    def SendHighway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.HighwaySender/SendHighway',
            highway__pb2.HighwayRequest.SerializeToString,
            highway__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
